# Site

title: Smart and Interactive Documents
handouts:
  - worksheet.Rmd
  - worksheet.R
  - data/animals.csv
  - data/species.csv
  - data/README.md
tag: v0.2
lesson: 9
instructor:
authors:
  - Ian Carroll
  - Kelly Hondula

# Slides

slide_sorter:
  - intro
  - markdown
  - rmarkdown
  - pipeline
  - shiny
  - conclude
  - exercises

#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/v2.0/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

markdown: kramdown
collections:
  - slides
